# Architecture
arch: c100WideResNet28_10

# ===== Dataset ===== #
data: datasets
set: CIFAR100
name: baseline

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1
lr_policy: milestone_lr
miestones: "80,120"

# ===== Network training config ===== #
epochs: 200
weight_decay: 0.0005
momentum: 0.9
batch_size: 128

# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: NonAffineBatchNorm
init: kaiming_normal
mode: fan_in
nonlinearity: relu
prune_rate: -1
scale_fan: True
freeze_weights: True

# ===== Hardware setup ===== #
workers: 4